[package]

name = "nickel_redis"
version = "0.1.1"
authors = [
    "bguiz",
    "qio"
]

[dependencies]
r2d2 = "*"
plugin = "*"
typemap = "*"
openssl = "*"
nickel = "*"
redis = "0.5.1"

[dependencies.r2d2_redis]
git = "https://github.com/nevdelap/r2d2-redis.git"
