[package]

name = "nickel_redis"
version = "0.1.1"
authors = [
    "bguiz",
    "qio"
]

[dependencies]
r2d2 = "*"
r2d2_redis = "*"
plugin = "*"
typemap = "*"
openssl = "*"
nickel = "*"

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"
